@startuml

title __HOSPITAL's Class Diagram__\n

  namespace tps.tp4 {
    class tps.tp4.Admin {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Admin {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.App {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.App {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.CmdSistema {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.CmdSistema {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Consulta {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Consulta {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Doente {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Doente {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Enfermeiro {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Enfermeiro {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.InterApp {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Login {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Login {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Medico {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Medico {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.MyApp {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Sistema {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.Sistema {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.SistemaBD {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.SistemaBD {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.User {
    }
  }
  

  namespace tps.tp4 {
    class tps.tp4.User {
    }
  }
  

  tps.tp4.Admin -up-|> tps.tp4.User
  tps.tp4.Admin -up-|> tps.tp4.User
  tps.tp4.Doente -up-|> tps.tp4.User
  tps.tp4.Doente -up-|> tps.tp4.User
  tps.tp4.Enfermeiro -up-|> tps.tp4.User
  tps.tp4.Enfermeiro -up-|> tps.tp4.User
  tps.tp4.Medico -up-|> tps.tp4.User
  tps.tp4.Medico -up-|> tps.tp4.User
  tps.tp4.MyApp -up-|> javax.swing.JFrame
  tps.tp4.Sistema -up-|> tps.tp4.Login


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
